bsit_2020/urls.py
from django.contrib import admin
from django.urls import path, include
from content import views as content_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', content_views.content_create),
    path('snc-bsit/', include('content.urls')),
]

urlpatterns += staticfiles_urlpatterns()

content/urls.py
from django.urls import path
from . import views

app_name="content"

urlpatterns = [
    path('create/', views.content_create, name="create"),
    path('create/<id>', views.content_create, name="create"),
    path('list/', views.content_list, name="list"),
    path('list/', views.content_list, name="list"),
    path('dNUGnnVwy9zQyIkigk9D6vtoSBqhyM9jSS1IiT1fU/<int:id>', views.content_delete, name="delete"),
]

content/models.py
from django.db import models

# Create your models here.
class BsitEmail(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField()
    date_created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.fullname

content/forms.py
from django import forms
from . import models

class StudentForm(forms.ModelForm):
    class Meta:
        model = models.BsitEmail
        fields = ['fullname', 'email']

        widgets = {
            'fullname' : forms.TextInput(attrs={
                "placeholder":"e.g Lastname, Firstname M.I",
                "minlength":"4",
                "class":"form-control btn-block",
                "autocomplete":"off",
            }),
            'email' : forms.TextInput(attrs={
                "data-rule":"required",
                "minlength":"4",
                "class":"form-control ",
                "placeholder": "e.g myusername@gmail.com",
                "autocomplete":"off",

            })
        }

content/views.py
from django.shortcuts import render, redirect


from . import forms
from .import models

def content_create(request, id=0):
    if id == 0:
        if request.method == 'GET':
            form = forms.StudentForm()
            return render(request, 'content/content_index.html', { 'forms':form ,'active1':'active'})
        elif request.method == 'POST':
            form = forms.StudentForm(data=request.POST)
            if form.is_valid():
                form.save()
                return redirect('content:list')              
    else:
        student = models.BsitEmail.objects.get(id=id)
        if request.method == 'GET':
            form = forms.StudentForm(instance=student)
            return render(request, 'content/content_index.html', { 'forms':form,'active1':'active'})
        
        elif request.method == 'POST':
            form = forms.StudentForm(request.POST, instance=student) 
            if form.is_valid():
                form.save()
                return redirect('content:list')



def content_list(request):
    students = models.BsitEmail.objects.all().order_by('fullname')
    return render(request, 'content/content_list.html', {'students':students,'active2':'active'})


def content_delete(request, id):
    try:   
        student = models.BsitEmail.objects.get(id=id)
        student.delete()
        return redirect('content:list')
    except Exception as e:
        return redirect('content:list')

content/templates/content/content_delete.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="col-sm-6 offset-sm-3 mod-form">
        
    </div>

    <script>
        $(document).ready(function(){
            $('#btnSubmit').on('submit', function(){
                $('#btnSubmit').attr('type', 'button');
            })
        })

    </script>

    <style>

        .mod-form{
            border:1px solid rgb(46, 44, 44);
            padding:30px 30px;
            border-radius:10px;
            background-color:rgba(34, 33, 33, 0.514);
            margin-top:100px;
        }

        #id_fullname, #id_email, #id_submit{
            margin-bottom:10px;
        }

        input, #id_fullname, #id_email{
            background-color:rgba(19, 18, 18, 0.521);
            border:none;
            color:white;
        }

        label{
            color:white;
        }
    </style>
    
{% endblock %}

content/templates/content/content_index.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="col-sm-6 offset-sm-3 mod-form">
        <form action="" method="POST">
            {% csrf_token %}
            {{ forms }}
            <div class="col-sm-6 offset-sm-6">
                <div class="row">
                    <button type="submit" id="btnSubmit" class="btn btn-success btn-block">Submit</button>
                </div>
            </div>
        </form>
    </div>

    <script>

        $(document).ready(function(){
            $('form').on('submit', function(){
                $('#btnSubmit').attr('type', 'button');
            })
        })


    </script>

    <style>

        .mod-form{
            border:1px solid rgb(46, 44, 44);
            padding:30px 30px;
            border-radius:10px;
            background-color:rgba(34, 33, 33, 0.514);
            margin-top:100px;
        }

        #id_fullname, #id_email, #id_submit{
            margin-bottom:10px;
        }

        input, #id_fullname, #id_email{
            background-color:rgba(19, 18, 18, 0.521);
            border:none;
            color:white;
        }

        label{
            color:white;
        }

        .btn-success{
            background-color:rgba(85, 209, 116, 0.521);
        }
    </style>
    
{% endblock %}

content/templates/content/content_list.html
{% extends 'base_layout.html' %}
{% block content %}

    <div class="col-sm-10 offset-sm-1 mod-form">
        <div class="row">
        <div class="col-sm-6">
            <h3 class="h3">SNC BSIT</h3>
        </div>
        <div class="col-sm-6">
            <input type="text" id="myInput" class="form-control btn-block modTextbox" placeholder="Search Here...">
        </div>
        </div>
        
        <table id="myTable" class="table table-sm table-dark table-bordered">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Fullname</th>
                <th class="d-none d-md-block" scope="col">Email</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for student in students%}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ student.fullname }}</td>
                        <td class="d-none d-md-block">{{ student.email }}</td>
                        <td>
                            &nbsp<a href="{% url 'content:create' student.id%}" class="btn-edit"><span class="fa fa-pencil" title="Edit"></span></a>
                            <button data-id="{{ student.email }}" class="btn-copy"><span class="fa fa-clone" title="Copy Email"></span></button>
                            &nbsp<button data-delete="{{ student.id }}" class="btn-delete d-none d-md-block"><span class="fa fa-trash" title="delete"></span></button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>

    <script>

        $('document').ready(function(){


            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

            $('.btn-copy').on('click', function(){
                value = $(this).data("id");
                var $temp = $("<input>");
                $("body").append($temp);
                $temp.val(value).select();
                document.execCommand("copy");
                $temp.remove();
                alert(value + " copied to clipboard")
            })


            $('.btn-edit').on('click', function(){
                value = $('.btn-edit').data("edit");
                $('.btn-edit').attr('span','')
                window.location.href = "{% url 'content:create' %}" + value;
            })


            
            $('.btn-delete').on('click', function(){
                value = $(this).data("delete");
                window.location.href = "/snc-bsit/dNUGnnVwy9zQyIkigk9D6vtoSBqhyM9jSS1IiT1fU/" + value;
            })

        })
    </script>

    <style>

        .modTextbox{
            border:1px solid rgba(151, 148, 148, 0.705);
            background-color:rgba(27, 26, 26, 0.315);
        }

        .table-dark thead{
            background-color:rgba(26, 25, 25, 0.842) !important;
        }

        .table-dark tbody{
            color:rgba(223, 211, 211, 0.959) !important;
        }

        .table-bordered tbody tr td{
            border:none;
            border-bottom:1px solid rgba(148, 145, 145, 0.315);
        }

        .table-bordered thead tr th{
            border:none;
            border-bottom:1px solid rgba(148, 145, 145, 0.315);
            border-top:1px solid rgba(148, 145, 145, 0.315);
        }

        .btn-edit:hover{
            color:rgb(197, 196, 196);
        }

        .table-dark{
            background-color:rgba(27, 26, 26, 0.315);
        }

        .modTextbox{
            border-radius:0 !important;
        }

        .btn-copy, .btn-edit{
            border:none;
            background-color:rgba(1, 1, 1, 0);
            color:rgb(199, 192, 192);
            margin-right:5px;
        }

        .btn-delete{
            float:left;
            border:none;
            background-color:rgba(1, 1, 1, 0);
            color:rgb(199, 192, 192);
            margin-right:5px;
        }

        .mod-form{
            margin-top:100px;
        }

        tbody{
            background-color:rgba(27, 26, 26, 0.315);
        }
        .h3{
            color:white !important;
        }
    
    </style>
    
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{%static 'snc.jpg' %}" rel="icon">
    <title>
        {% block title%}

        {% endblock %}
    </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="">SNC BSIT 2020</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link  {% if active1 == 'active'%}{{active1}}{%endif%}" href="{%url 'content:create'%}">Create</a>
            </li>
            <li class="nav-item">
                <a class="nav-link  {% if active2 == 'active'%}{{active2}}{%endif%}" href="{%url 'content:list'%}">List</a>
            </li>
          </ul>
        </div>
      </nav>
      

      <style>

            body{
                background-image:url('{%static "bg.jpg"%}');
                background-repeat: no-repeat;
                background-attachment: fixed;
            }

          .btnLogout{
              border:none;
              background-color:rgba(43, 43, 43, 0.001);
              color:red;
              float:left;
          }
      </style>
    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>